# Site settings
title: 'Michelle Lynn Gill, Ph.D.'
title2: 'Data Scientist & Biophysicist'
description: '<p>I am a data scientist and biophysicist located in New York City. My Ph.D. is in Molecular Biophysics & Biochemistry.</br></br>
When not thinking about data science, I enjoy programming in Python, all things made by Apple, running, Kansas basketball (Go Jayhawks!), 
and my collection of shoes.</p>'
url: 'http://michellelynngill.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'


external:
  blog:
    title: 'themodernscientist'
    url: http://themodernscientist.com
  cv:
    url: http://cv.michellelynngill.com
  resume:
    url: http://resume.michellelynngill.com

author:
  name: 'Michelle Gill'
  email: 'michelle@michellelynngill.com'
  twitter_username: 'modernscientist'
  github_username:  'mlgill'
  linkedin_username:  'michellelynngill'


# Build settings
destination: _site


gems: []
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'publish.sh']
