# Site settings
title: 'Michelle Lynn Gill, Ph.D.'
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'


author:
  name: 'Michelle Gill'
  email: 'michelle@michellelynngill.com'
  twitter_username: 'modernscientist'
  github_username:  'mlgill'
  linkedin_username:  'michellelynngill'


blog:
  title: 'themodernscientist'
  url: 'http://themodernscientist.com'


cv:
  url: 'http://cv.michellelynngill.com'


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
