name: Maintained file formatting

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: npm
      - name: Install Prettier 💾
        run: npm ci
      - name: Prettier Check 🔎
        run: npx prettier --check README.md TODO.md package.json scripts/package.json 'scripts/*.js' 'scripts/tests/**/*.mjs' '.github/workflows/*.yml'
